version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
        - "${POSTGRES_PORT}:5432"
    env_file:
        - .env
  redis:
    image: redis
    restart: always
    ports:
        - "${REDIS_PORT}:6379"
    env_file:
        - .env